language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

before_script:
    - composer install --prefer-source

script:
    - phpunit --configuration phpunit.xml.dist --coverage-text